# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather app
  pod 'GooglePlaces', '6.0.0'


  target 'Weather appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Weather appUITests' do
    # Pods for testing
  end

end
